spring:
  application:
    name: community
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.nowcoder.community.entity
    configuration:
      useGeneratedKeys: true
      mapUnderscoreToCamelCase: true
  logging:
    level:
      com:
        nowcoder:
          community:
            controller: debug
  mail:
    host: smtp.qq.com
    port: 456
    username: nowcoder@qq.com
    password: nowcoder123
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true